### ISSUE TITLE
Eris for Lua 5.3

### ISSUE THREAD

**Issue by fnuecke** [fnuecke/eris#12]
I have ported Eris to Lua 5.3 (in the `Lua5.3` branch).

All tests pass, so things are looking good, but it'll need some more long-term testing to verify that nothing sneakily breaks in unexpected places.

**Comment by SirVer** [comment]
Widelands would switch to Lua 5.3 as soon as you deem it stable enough.

**Comment by fnuecke** [comment]
I've found an issue related to persisted upvalues, can't quite pin it down yet. Not sure if the references get mangled when writing, or something messes up while loading.

I'll work on it as time permits; may have to come up with a different way to manage upvalue persistence.

If someone else wants to bang their head against this, too, I'd be happy for input ;-)

**Comment by daurnimator** [comment]
:+1:

**Comment by fnuecke** [comment]
All right, I finally had the time to dig into the code a again, and I finally found the upvalue bug. I think, anyway. At least everything looks to be working fine for me now.

If you'd like to give it a try, check out the [master-lua5.3 branch](https://github.com/fnuecke/eris/tree/master-lua5.3).

**Important**: keep in mind that the save format between 5.2 and 5.3 is *not* compatible, amongst other things because of the new integer type in 5.3.

**Comment by fnuecke** [comment]
All right, I've had it running in the wild for a while now, and haven't gotten any reports of it breaking yet, so I'm somewhat confident it's properly working now!
