### ISSUE TITLE
Linking issue when compiling eris as C++ caused by "typedef int bool"

### ISSUE THREAD

**Issue by cbeck88** [fnuecke/eris#21]
In `eris.c` there are some compatibility declarations for MSVC I guess containing

```
/* Not using stdbool because Visual Studio lives in the past... */
typedef int bool;
#define false 0
#define true 1
```

Later we get extern declarations so we can see the `eris_permXlib` functions:

```
/* Functions in Lua libraries used to access C functions we need to add to the
 * permanents table to fully support yielded coroutines. */
extern void eris_permbaselib(lua_State *L, bool forUnpersist);
extern void eris_permcorolib(lua_State *L, bool forUnpersist);
extern void eris_permloadlib(lua_State *L, bool forUnpersist);
extern void eris_permiolib(lua_State *L, bool forUnpersist);
extern void eris_permstrlib(lua_State *L, bool forUnpersist);
```

However the definitions of these functions in each of the actual library `.c` files are like this

```
void eris_permbaselib(lua_State *L, int forUnpersist) {
```

In C I guess this works, but modern C++ compilers are basically configured to ignore things like `typedef int bool` and `#define true 1`, because although this is common in C headers, `bool` and `true` are part of the C++ language, unlike how they are handled in C.

In C++ `bool` and `int` are not the same type so the declarations and definitions don't match, which I think causes the linker error. In C they are the same so linking succeeds.

It took me a while to figure out why I could not link when compiling eris as c++, if you would like a patch that changes the `bool` declarations to `int` or vice versa I would be happy to provide. It seems to fix the linking for me, and passes eris' internal tests as well as the internal tests of my project.

**Comment by fnuecke** [comment]
Thanks again for the PR! I had indeed not tried to compile it in a CPP context before. Glad to hear this is the only problem in that regard.
