### ISSUE TITLE
Please update the project description

### ISSUE THREAD

**Issue by mquinson** [fnuecke/eris#23]
From what I see in the release page, you are targeting Lua 5.3, but the short description and the main Readme.md state that you are targeting Lua 5.2. Could you please update this?

Thanks, Mt

**Comment by fnuecke** [comment]
The `master` branch actually does target 5.2. The [`master-lua5.3`](https://github.com/fnuecke/eris/tree/master-lua5.3) branch targets 5.3, and mentions this in the readme :)
