### ISSUE TITLE
Memory limit

### ISSUE THREAD

**Issue by Avaja** [fnuecke/eris#24]
I studied OpenComputers, and I want to know how to limit memory?

**Comment by fnuecke** [comment]
OpenComputers uses a slightly modified version of JNLua, [with a custom allocator](https://github.com/fnuecke/jnlua/blob/a8e95351a43a83ba0b9a3d5b7fa5e0a91eadeb36/jnlua/src/main/c/jnlua.c#L200-L259). Depending on your use case, it is more complex than necessary; but this generally applies: to limit memory, use a custom allocator and return `null` when trying to allocate but it'd exceed the memory limit.

**Comment by Avaja** [comment]
thanks for the answer!
I'll watch the code!
