### ISSUE TITLE
Internals of eris

### ISSUE THREAD

**Issue by LmTinyToon** [fnuecke/eris#25]
Thanks for such library. Is there any good articles about internals of eris? I want to learn internals to understand eris. I just want to find any article for quick start (it seems like there is no one).

**Comment by fnuecke** [comment]
Always happy to hear when it's helpful to people :)

I'm afraid there's no article specifically discussing the internals of Eris. Aside from the readme on the repo describing the high-level functionality, the [file format documentation](https://github.com/fnuecke/eris/blob/master/FILEFORMAT) is probably the most you can find before having to dig into the [actual code](https://github.com/fnuecke/eris/blob/master/src/eris.c).

Aside from details though, basically what happens is that [persist_typed](https://github.com/fnuecke/eris/blob/master/src/eris.c#L2071) is called starting with a root object to persist, and then possibly called recursively while traversing all references leading out from that root object -- so for [tables](https://github.com/fnuecke/eris/blob/master/src/eris.c#L905) all their keys and values, for [functions](https://github.com/fnuecke/eris/blob/master/src/eris.c#L1403) their upvalues, for [threads](https://github.com/fnuecke/eris/blob/master/src/eris.c#L1655) their stack etc. For deserialization it's the opposite process.

One thing that will help immensely while reading the code is understanding what the comments on the right of many lines mean: e.g. in [this line](https://github.com/fnuecke/eris/blob/master/src/eris.c#L909), it's `/* ... tbl nil */`. These comments document the state of the Lua stack after that line finished execution. So here the stack holds some values (`...`), a table (`tbl`) and a `nil` value (`nil`), which was just pushed onto the stack.

If you have any specific questions, let me know and I'll try to remember the answers to them.

**Comment by LmTinyToon** [comment]
Great thanks for reply (I have understood something from your code) . I will definitely ask questions (I need some time to learn sources of eris).
