### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by jreinkin** [fnuecke/eris#28]
set  `kWriteDebugInformation` to `false;`. Then persist and unpersist a lclosure. In the function `u_proto` the function will return earlier because of the missing debug information. 

/* Read debug information if any is present. */
  if (!READ_VALUE(uint8_t)) {
    return;
  }

Like expected there is a proto on top of the stack. So far so good. But when the function call returns to `u_closure` it pops the proto but also the function from the stack (`lua_pop(info->L, 2); /* ... lcl */`). With activated debug information `u_proto` would push 2 protos (`lua_pushvalue(info->L, -1); /* ... proto proto */`). I guess to make the assertion `eris_assert(top + 1 == lua_gettop(info->L));` happy. Solution: push also a second proto on the stack when leaving earlier with deactivated debug information.

/* Read debug information if any is present. */
  if (!READ_VALUE(uint8_t)) {
    lua_pushvalue(info->L, -1);
    return;
  }

**Comment by fnuecke** [comment]
Thanks for the detailed description! Sorry for the massive delay. Better late than never...
