### ISSUE TITLE
What is the purpose of persisting iolib and loadlib?

### ISSUE THREAD

**Issue by samhocevar** [fnuecke/eris#31]
I am embedding Eris in a stripped-down version of Lua that does not have iolib or loadlib. It appears to work fine.

However I noticed that even in the master Eris branch, when removing `eris_permloadlib` and `eris_permiolib`, the testsuite still passes. Could you maybe explain in what case these functions are required?

**Comment by fnuecke** [comment]
`iolib` pushes a C function through `io.lines` (part of the iterator), so I'm guessing there's no test for yielding out of a `for line in io.lines(filename) do ...`.

`loadlib` pushes a couple of C functions as searchers (for import resolving), I'm guessing no test persists anything referencing those.

(In both cases the C functions are what's added to the perms table.)

**Comment by samhocevar** [comment]
I believe you answered my question, thanks :-)
